/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface Blueprint extends AdditionalDataHolder, Parsable {
    /**
     * The build_cmd property
     */
    buildCmd?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The env_vars property
     */
    envVars?: Blueprint_env_vars | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The port property
     */
    port?: number | null;
    /**
     * The project_id property
     */
    projectId?: string | null;
    /**
     * The remote property
     */
    remote?: RemoteObj | null;
    /**
     * The run_cmd property
     */
    runCmd?: string | null;
    /**
     * The runtime property
     */
    runtime?: RuntimeObj | null;
    /**
     * The source property
     */
    source?: Blueprint_source | null;
    /**
     * The static_dir property
     */
    staticDir?: string | null;
    /**
     * The status property
     */
    status?: string | null;
    /**
     * The working_dir property
     */
    workingDir?: string | null;
}
export interface Blueprint_env_vars extends AdditionalDataHolder, Parsable {
}
export type Blueprint_source = (typeof Blueprint_sourceObject)[keyof typeof Blueprint_sourceObject];
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Blueprint_env_vars}
 */
// @ts-ignore
export function createBlueprint_env_varsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBlueprint_env_vars;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Blueprint}
 */
// @ts-ignore
export function createBlueprintFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBlueprint;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Deployment}
 */
// @ts-ignore
export function createDeploymentFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeployment;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeployRequest_env_vars}
 */
// @ts-ignore
export function createDeployRequest_env_varsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeployRequest_env_vars;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeployRequest_secrets}
 */
// @ts-ignore
export function createDeployRequest_secretsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeployRequest_secrets;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeployRequest}
 */
// @ts-ignore
export function createDeployRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeployRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeployResponse}
 */
// @ts-ignore
export function createDeployResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeployResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Error_details}
 */
// @ts-ignore
export function createError_detailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoError_details;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorEscaped}
 */
// @ts-ignore
export function createErrorEscapedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorEscaped;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProxyRoute}
 */
// @ts-ignore
export function createProxyRouteFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProxyRoute;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProxyStatus}
 */
// @ts-ignore
export function createProxyStatusFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProxyStatus;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterInstanceRequest}
 */
// @ts-ignore
export function createRegisterInstanceRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterInstanceRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RemoteObj}
 */
// @ts-ignore
export function createRemoteObjFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRemoteObj;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RuntimeObj}
 */
// @ts-ignore
export function createRuntimeObjFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRuntimeObj;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Service_env_vars}
 */
// @ts-ignore
export function createService_env_varsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoService_env_vars;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Service}
 */
// @ts-ignore
export function createServiceFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoService;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServiceUpdate_env_vars}
 */
// @ts-ignore
export function createServiceUpdate_env_varsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServiceUpdate_env_vars;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServiceUpdate}
 */
// @ts-ignore
export function createServiceUpdateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServiceUpdate;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemDoctorResult}
 */
// @ts-ignore
export function createSystemDoctorResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemDoctorResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemInfo_build}
 */
// @ts-ignore
export function createSystemInfo_buildFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemInfo_build;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemInfo_hardware}
 */
// @ts-ignore
export function createSystemInfo_hardwareFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemInfo_hardware;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemInfo_storage_devices}
 */
// @ts-ignore
export function createSystemInfo_storage_devicesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemInfo_storage_devices;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemInfo_storage_partitions}
 */
// @ts-ignore
export function createSystemInfo_storage_partitionsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemInfo_storage_partitions;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemInfo_storage}
 */
// @ts-ignore
export function createSystemInfo_storageFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemInfo_storage;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemInfo}
 */
// @ts-ignore
export function createSystemInfoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemInfo;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemStatus_proxy}
 */
// @ts-ignore
export function createSystemStatus_proxyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemStatus_proxy;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemStatus_services}
 */
// @ts-ignore
export function createSystemStatus_servicesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemStatus_services;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SystemStatus}
 */
// @ts-ignore
export function createSystemStatusFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSystemStatus;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ValidationError_details}
 */
// @ts-ignore
export function createValidationError_detailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoValidationError_details;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ValidationError}
 */
// @ts-ignore
export function createValidationErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoValidationError;
}
export interface Deployment extends AdditionalDataHolder, Parsable {
    /**
     * The config property
     */
    config?: Blueprint | null;
    /**
     * The created_at property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The metadata property
     */
    metadata?: string | null;
    /**
     * The status property
     */
    status?: DeploymentStatus | null;
    /**
     * The updated_at property
     */
    updatedAt?: Date | null;
    /**
     * Email of the user who created the deployment
     */
    userEmail?: string | null;
    /**
     * ID of the user who created the deployment
     */
    userId?: string | null;
}
export type DeploymentStatus = (typeof DeploymentStatusObject)[keyof typeof DeploymentStatusObject];
export interface DeployRequest extends AdditionalDataHolder, Parsable {
    /**
     * The build_cmd property
     */
    buildCmd?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The dns_provider property
     */
    dnsProvider?: string | null;
    /**
     * The domain property
     */
    domain?: string | null;
    /**
     * The env_vars property
     */
    envVars?: DeployRequest_env_vars | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The port property
     */
    port?: number | null;
    /**
     * The remote property
     */
    remote?: RemoteObj | null;
    /**
     * The run_cmd property
     */
    runCmd?: string | null;
    /**
     * The runtime property
     */
    runtime?: RuntimeObj | null;
    /**
     * The secrets property
     */
    secrets?: DeployRequest_secrets | null;
    /**
     * The source property
     */
    source?: DeployRequest_source | null;
    /**
     * The static_dir property
     */
    staticDir?: string | null;
    /**
     * The user_id property
     */
    userId?: string | null;
    /**
     * The version property
     */
    version?: string | null;
    /**
     * The working_dir property
     */
    workingDir?: string | null;
}
export interface DeployRequest_env_vars extends AdditionalDataHolder, Parsable {
}
export interface DeployRequest_secrets extends AdditionalDataHolder, Parsable {
}
export type DeployRequest_source = (typeof DeployRequest_sourceObject)[keyof typeof DeployRequest_sourceObject];
export interface DeployResponse extends AdditionalDataHolder, Parsable {
    /**
     * The created_at property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
/**
 * The deserialization information for the current model
 * @param Blueprint The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBlueprint(blueprint: Partial<Blueprint> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "build_cmd": n => { blueprint.buildCmd = n.getStringValue(); },
        "description": n => { blueprint.description = n.getStringValue(); },
        "env_vars": n => { blueprint.envVars = n.getObjectValue<Blueprint_env_vars>(createBlueprint_env_varsFromDiscriminatorValue); },
        "image": n => { blueprint.image = n.getStringValue(); },
        "name": n => { blueprint.name = n.getStringValue(); },
        "port": n => { blueprint.port = n.getNumberValue(); },
        "project_id": n => { blueprint.projectId = n.getStringValue(); },
        "remote": n => { blueprint.remote = n.getObjectValue<RemoteObj>(createRemoteObjFromDiscriminatorValue); },
        "run_cmd": n => { blueprint.runCmd = n.getStringValue(); },
        "runtime": n => { blueprint.runtime = n.getObjectValue<RuntimeObj>(createRuntimeObjFromDiscriminatorValue); },
        "source": n => { blueprint.source = n.getEnumValue<Blueprint_source>(Blueprint_sourceObject); },
        "static_dir": n => { blueprint.staticDir = n.getStringValue(); },
        "status": n => { blueprint.status = n.getStringValue(); },
        "working_dir": n => { blueprint.workingDir = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Blueprint_env_vars The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBlueprint_env_vars(blueprint_env_vars: Partial<Blueprint_env_vars> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param Deployment The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeployment(deployment: Partial<Deployment> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "config": n => { deployment.config = n.getObjectValue<Blueprint>(createBlueprintFromDiscriminatorValue); },
        "created_at": n => { deployment.createdAt = n.getDateValue(); },
        "id": n => { deployment.id = n.getStringValue(); },
        "metadata": n => { deployment.metadata = n.getStringValue(); },
        "status": n => { deployment.status = n.getEnumValue<DeploymentStatus>(DeploymentStatusObject); },
        "updated_at": n => { deployment.updatedAt = n.getDateValue(); },
        "user_email": n => { deployment.userEmail = n.getStringValue(); },
        "user_id": n => { deployment.userId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DeployRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeployRequest(deployRequest: Partial<DeployRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "build_cmd": n => { deployRequest.buildCmd = n.getStringValue(); },
        "description": n => { deployRequest.description = n.getStringValue(); },
        "dns_provider": n => { deployRequest.dnsProvider = n.getStringValue(); },
        "domain": n => { deployRequest.domain = n.getStringValue(); },
        "env_vars": n => { deployRequest.envVars = n.getObjectValue<DeployRequest_env_vars>(createDeployRequest_env_varsFromDiscriminatorValue); },
        "image": n => { deployRequest.image = n.getStringValue(); },
        "name": n => { deployRequest.name = n.getStringValue(); },
        "port": n => { deployRequest.port = n.getNumberValue(); },
        "remote": n => { deployRequest.remote = n.getObjectValue<RemoteObj>(createRemoteObjFromDiscriminatorValue); },
        "run_cmd": n => { deployRequest.runCmd = n.getStringValue(); },
        "runtime": n => { deployRequest.runtime = n.getObjectValue<RuntimeObj>(createRuntimeObjFromDiscriminatorValue); },
        "secrets": n => { deployRequest.secrets = n.getObjectValue<DeployRequest_secrets>(createDeployRequest_secretsFromDiscriminatorValue); },
        "source": n => { deployRequest.source = n.getEnumValue<DeployRequest_source>(DeployRequest_sourceObject); },
        "static_dir": n => { deployRequest.staticDir = n.getStringValue(); },
        "user_id": n => { deployRequest.userId = n.getStringValue(); },
        "version": n => { deployRequest.version = n.getStringValue(); },
        "working_dir": n => { deployRequest.workingDir = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DeployRequest_env_vars The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeployRequest_env_vars(deployRequest_env_vars: Partial<DeployRequest_env_vars> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DeployRequest_secrets The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeployRequest_secrets(deployRequest_secrets: Partial<DeployRequest_secrets> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DeployResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeployResponse(deployResponse: Partial<DeployResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "created_at": n => { deployResponse.createdAt = n.getDateValue(); },
        "id": n => { deployResponse.id = n.getStringValue(); },
        "name": n => { deployResponse.name = n.getStringValue(); },
        "success": n => { deployResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Error_details The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoError_details(error_details: Partial<Error_details> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorEscaped The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorEscaped(errorEscaped: Partial<ErrorEscaped> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { errorEscaped.code = n.getStringValue(); },
        "details": n => { errorEscaped.details = n.getObjectValue<Error_details>(createError_detailsFromDiscriminatorValue); },
        "error": n => { errorEscaped.errorEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProxyRoute The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProxyRoute(proxyRoute: Partial<ProxyRoute> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "domain": n => { proxyRoute.domain = n.getStringValue(); },
        "upstream": n => { proxyRoute.upstream = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProxyStatus The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProxyStatus(proxyStatus: Partial<ProxyStatus> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "status": n => { proxyStatus.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RegisterInstanceRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterInstanceRequest(registerInstanceRequest: Partial<RegisterInstanceRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "audience": n => { registerInstanceRequest.audience = n.getStringValue(); },
        "claim": n => { registerInstanceRequest.claim = n.getStringValue(); },
        "instance_id": n => { registerInstanceRequest.instanceId = n.getStringValue(); },
        "issuer": n => { registerInstanceRequest.issuer = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RemoteObj The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRemoteObj(remoteObj: Partial<RemoteObj> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "branch": n => { remoteObj.branch = n.getStringValue(); },
        "commit_hash": n => { remoteObj.commitHash = n.getStringValue(); },
        "url": n => { remoteObj.url = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RuntimeObj The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRuntimeObj(runtimeObj: Partial<RuntimeObj> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "type": n => { runtimeObj.type = n.getEnumValue<Runtime>(RuntimeObject); },
        "version": n => { runtimeObj.version = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Service The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoService(service: Partial<Service> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "blueprint": n => { service.blueprint = n.getObjectValue<Blueprint>(createBlueprintFromDiscriminatorValue); },
        "branch": n => { service.branch = n.getStringValue(); },
        "build_cmd": n => { service.buildCmd = n.getStringValue(); },
        "commit_hash": n => { service.commitHash = n.getStringValue(); },
        "created_at": n => { service.createdAt = n.getDateValue(); },
        "description": n => { service.description = n.getStringValue(); },
        "env_vars": n => { service.envVars = n.getObjectValue<Service_env_vars>(createService_env_varsFromDiscriminatorValue); },
        "id": n => { service.id = n.getStringValue(); },
        "image": n => { service.image = n.getStringValue(); },
        "name": n => { service.name = n.getStringValue(); },
        "port": n => { service.port = n.getNumberValue(); },
        "remote": n => { service.remote = n.getStringValue(); },
        "run_cmd": n => { service.runCmd = n.getStringValue(); },
        "runtime": n => { service.runtime = n.getEnumValue<Runtime>(RuntimeObject); },
        "runtime_version": n => { service.runtimeVersion = n.getStringValue(); },
        "source": n => { service.source = n.getStringValue(); },
        "static_dir": n => { service.staticDir = n.getStringValue(); },
        "status": n => { service.status = n.getStringValue(); },
        "updated_at": n => { service.updatedAt = n.getDateValue(); },
        "working_dir": n => { service.workingDir = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Service_env_vars The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoService_env_vars(service_env_vars: Partial<Service_env_vars> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param ServiceUpdate The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServiceUpdate(serviceUpdate: Partial<ServiceUpdate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "branch": n => { serviceUpdate.branch = n.getStringValue(); },
        "build_cmd": n => { serviceUpdate.buildCmd = n.getStringValue(); },
        "description": n => { serviceUpdate.description = n.getStringValue(); },
        "env_vars": n => { serviceUpdate.envVars = n.getObjectValue<ServiceUpdate_env_vars>(createServiceUpdate_env_varsFromDiscriminatorValue); },
        "image": n => { serviceUpdate.image = n.getStringValue(); },
        "name": n => { serviceUpdate.name = n.getStringValue(); },
        "port": n => { serviceUpdate.port = n.getNumberValue(); },
        "run_cmd": n => { serviceUpdate.runCmd = n.getStringValue(); },
        "runtime_version": n => { serviceUpdate.runtimeVersion = n.getStringValue(); },
        "static_dir": n => { serviceUpdate.staticDir = n.getStringValue(); },
        "working_dir": n => { serviceUpdate.workingDir = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ServiceUpdate_env_vars The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServiceUpdate_env_vars(serviceUpdate_env_vars: Partial<ServiceUpdate_env_vars> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param SystemDoctorResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemDoctorResult(systemDoctorResult: Partial<SystemDoctorResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { systemDoctorResult.errorEscaped = n.getStringValue(); },
        "output": n => { systemDoctorResult.output = n.getStringValue(); },
        "status": n => { systemDoctorResult.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemInfo The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemInfo(systemInfo: Partial<SystemInfo> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "build": n => { systemInfo.build = n.getObjectValue<SystemInfo_build>(createSystemInfo_buildFromDiscriminatorValue); },
        "hardware": n => { systemInfo.hardware = n.getObjectValue<SystemInfo_hardware>(createSystemInfo_hardwareFromDiscriminatorValue); },
        "storage": n => { systemInfo.storage = n.getObjectValue<SystemInfo_storage>(createSystemInfo_storageFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemInfo_build The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemInfo_build(systemInfo_build: Partial<SystemInfo_build> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "build_date": n => { systemInfo_build.buildDate = n.getStringValue(); },
        "commit": n => { systemInfo_build.commit = n.getStringValue(); },
        "go_version": n => { systemInfo_build.goVersion = n.getStringValue(); },
        "version": n => { systemInfo_build.version = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemInfo_hardware The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemInfo_hardware(systemInfo_hardware: Partial<SystemInfo_hardware> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "arch": n => { systemInfo_hardware.arch = n.getStringValue(); },
        "cpu_count": n => { systemInfo_hardware.cpuCount = n.getNumberValue(); },
        "hostname": n => { systemInfo_hardware.hostname = n.getStringValue(); },
        "kernel": n => { systemInfo_hardware.kernel = n.getStringValue(); },
        "mem_free": n => { systemInfo_hardware.memFree = n.getStringValue(); },
        "mem_total": n => { systemInfo_hardware.memTotal = n.getStringValue(); },
        "mem_used": n => { systemInfo_hardware.memUsed = n.getStringValue(); },
        "os": n => { systemInfo_hardware.os = n.getStringValue(); },
        "swap_total": n => { systemInfo_hardware.swapTotal = n.getStringValue(); },
        "swap_used": n => { systemInfo_hardware.swapUsed = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemInfo_storage The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemInfo_storage(systemInfo_storage: Partial<SystemInfo_storage> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "devices": n => { systemInfo_storage.devices = n.getCollectionOfObjectValues<SystemInfo_storage_devices>(createSystemInfo_storage_devicesFromDiscriminatorValue); },
        "partitions": n => { systemInfo_storage.partitions = n.getCollectionOfObjectValues<SystemInfo_storage_partitions>(createSystemInfo_storage_partitionsFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemInfo_storage_devices The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemInfo_storage_devices(systemInfo_storage_devices: Partial<SystemInfo_storage_devices> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "mountpoints": n => { systemInfo_storage_devices.mountpoints = n.getCollectionOfPrimitiveValues<string>(); },
        "name": n => { systemInfo_storage_devices.name = n.getStringValue(); },
        "size": n => { systemInfo_storage_devices.size = n.getStringValue(); },
        "type": n => { systemInfo_storage_devices.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemInfo_storage_partitions The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemInfo_storage_partitions(systemInfo_storage_partitions: Partial<SystemInfo_storage_partitions> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "available": n => { systemInfo_storage_partitions.available = n.getStringValue(); },
        "filesystem": n => { systemInfo_storage_partitions.filesystem = n.getStringValue(); },
        "mountpoint": n => { systemInfo_storage_partitions.mountpoint = n.getStringValue(); },
        "size": n => { systemInfo_storage_partitions.size = n.getStringValue(); },
        "used": n => { systemInfo_storage_partitions.used = n.getStringValue(); },
        "use_percent": n => { systemInfo_storage_partitions.usePercent = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemStatus The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemStatus(systemStatus: Partial<SystemStatus> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "proxy": n => { systemStatus.proxy = n.getObjectValue<SystemStatus_proxy>(createSystemStatus_proxyFromDiscriminatorValue); },
        "services": n => { systemStatus.services = n.getObjectValue<SystemStatus_services>(createSystemStatus_servicesFromDiscriminatorValue); },
        "status": n => { systemStatus.status = n.getEnumValue<SystemStatus_status>(SystemStatus_statusObject); },
        "uptime": n => { systemStatus.uptime = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemStatus_proxy The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemStatus_proxy(systemStatus_proxy: Partial<SystemStatus_proxy> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "routes": n => { systemStatus_proxy.routes = n.getNumberValue(); },
        "status": n => { systemStatus_proxy.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SystemStatus_services The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSystemStatus_services(systemStatus_services: Partial<SystemStatus_services> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "running": n => { systemStatus_services.running = n.getNumberValue(); },
        "stopped": n => { systemStatus_services.stopped = n.getNumberValue(); },
        "total": n => { systemStatus_services.total = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ValidationError The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoValidationError(validationError: Partial<ValidationError> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "details": n => { validationError.details = n.getCollectionOfObjectValues<ValidationError_details>(createValidationError_detailsFromDiscriminatorValue); },
        "error": n => { validationError.errorEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ValidationError_details The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoValidationError_details(validationError_details: Partial<ValidationError_details> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "field": n => { validationError_details.field = n.getStringValue(); },
        "message": n => { validationError_details.message = n.getStringValue(); },
    }
}
/**
 * Additional error details
 */
export interface Error_details extends AdditionalDataHolder, Parsable {
}
export interface ErrorEscaped extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Error code
     */
    code?: string | null;
    /**
     * Additional error details
     */
    details?: Error_details | null;
    /**
     * Error message
     */
    errorEscaped?: string | null;
}
export interface ProxyRoute extends AdditionalDataHolder, Parsable {
    /**
     * The domain property
     */
    domain?: string | null;
    /**
     * The upstream property
     */
    upstream?: string | null;
}
export interface ProxyStatus extends AdditionalDataHolder, Parsable {
    /**
     * The status property
     */
    status?: string | null;
}
export interface RegisterInstanceRequest extends AdditionalDataHolder, Parsable {
    /**
     * Expected token audience (for validation)
     */
    audience?: string | null;
    /**
     * Signed claim token issued by base
     */
    claim?: string | null;
    /**
     * Unique identifier assigned to this instance by base
     */
    instanceId?: string | null;
    /**
     * Expected token issuer (for validation)
     */
    issuer?: string | null;
}
export interface RemoteObj extends AdditionalDataHolder, Parsable {
    /**
     * The branch property
     */
    branch?: string | null;
    /**
     * The commit_hash property
     */
    commitHash?: string | null;
    /**
     * The url property
     */
    url?: string | null;
}
export type Runtime = (typeof RuntimeObject)[keyof typeof RuntimeObject];
export interface RuntimeObj extends AdditionalDataHolder, Parsable {
    /**
     * The type property
     */
    type?: Runtime | null;
    /**
     * The version property
     */
    version?: string | null;
}
/**
 * Serializes information the current object
 * @param Blueprint The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBlueprint(writer: SerializationWriter, blueprint: Partial<Blueprint> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!blueprint || isSerializingDerivedType) { return; }
    writer.writeStringValue("build_cmd", blueprint.buildCmd);
    writer.writeStringValue("description", blueprint.description);
    writer.writeObjectValue<Blueprint_env_vars>("env_vars", blueprint.envVars, serializeBlueprint_env_vars);
    writer.writeStringValue("image", blueprint.image);
    writer.writeStringValue("name", blueprint.name);
    writer.writeNumberValue("port", blueprint.port);
    writer.writeStringValue("project_id", blueprint.projectId);
    writer.writeObjectValue<RemoteObj>("remote", blueprint.remote, serializeRemoteObj);
    writer.writeStringValue("run_cmd", blueprint.runCmd);
    writer.writeObjectValue<RuntimeObj>("runtime", blueprint.runtime, serializeRuntimeObj);
    writer.writeEnumValue<Blueprint_source>("source", blueprint.source);
    writer.writeStringValue("static_dir", blueprint.staticDir);
    writer.writeStringValue("status", blueprint.status);
    writer.writeStringValue("working_dir", blueprint.workingDir);
    writer.writeAdditionalData(blueprint.additionalData);
}
/**
 * Serializes information the current object
 * @param Blueprint_env_vars The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBlueprint_env_vars(writer: SerializationWriter, blueprint_env_vars: Partial<Blueprint_env_vars> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!blueprint_env_vars || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(blueprint_env_vars.additionalData);
}
/**
 * Serializes information the current object
 * @param Deployment The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeployment(writer: SerializationWriter, deployment: Partial<Deployment> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deployment || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Blueprint>("config", deployment.config, serializeBlueprint);
    writer.writeDateValue("created_at", deployment.createdAt);
    writer.writeStringValue("id", deployment.id);
    writer.writeStringValue("metadata", deployment.metadata);
    writer.writeEnumValue<DeploymentStatus>("status", deployment.status);
    writer.writeDateValue("updated_at", deployment.updatedAt);
    writer.writeStringValue("user_email", deployment.userEmail);
    writer.writeStringValue("user_id", deployment.userId);
    writer.writeAdditionalData(deployment.additionalData);
}
/**
 * Serializes information the current object
 * @param DeployRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeployRequest(writer: SerializationWriter, deployRequest: Partial<DeployRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deployRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("build_cmd", deployRequest.buildCmd);
    writer.writeStringValue("description", deployRequest.description);
    writer.writeStringValue("dns_provider", deployRequest.dnsProvider);
    writer.writeStringValue("domain", deployRequest.domain);
    writer.writeObjectValue<DeployRequest_env_vars>("env_vars", deployRequest.envVars, serializeDeployRequest_env_vars);
    writer.writeStringValue("image", deployRequest.image);
    writer.writeStringValue("name", deployRequest.name);
    writer.writeNumberValue("port", deployRequest.port);
    writer.writeObjectValue<RemoteObj>("remote", deployRequest.remote, serializeRemoteObj);
    writer.writeStringValue("run_cmd", deployRequest.runCmd);
    writer.writeObjectValue<RuntimeObj>("runtime", deployRequest.runtime, serializeRuntimeObj);
    writer.writeObjectValue<DeployRequest_secrets>("secrets", deployRequest.secrets, serializeDeployRequest_secrets);
    writer.writeEnumValue<DeployRequest_source>("source", deployRequest.source);
    writer.writeStringValue("static_dir", deployRequest.staticDir);
    writer.writeStringValue("user_id", deployRequest.userId);
    writer.writeStringValue("version", deployRequest.version);
    writer.writeStringValue("working_dir", deployRequest.workingDir);
    writer.writeAdditionalData(deployRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param DeployRequest_env_vars The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeployRequest_env_vars(writer: SerializationWriter, deployRequest_env_vars: Partial<DeployRequest_env_vars> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deployRequest_env_vars || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(deployRequest_env_vars.additionalData);
}
/**
 * Serializes information the current object
 * @param DeployRequest_secrets The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeployRequest_secrets(writer: SerializationWriter, deployRequest_secrets: Partial<DeployRequest_secrets> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deployRequest_secrets || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(deployRequest_secrets.additionalData);
}
/**
 * Serializes information the current object
 * @param DeployResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeployResponse(writer: SerializationWriter, deployResponse: Partial<DeployResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deployResponse || isSerializingDerivedType) { return; }
    writer.writeDateValue("created_at", deployResponse.createdAt);
    writer.writeStringValue("id", deployResponse.id);
    writer.writeStringValue("name", deployResponse.name);
    writer.writeBooleanValue("success", deployResponse.success);
    writer.writeAdditionalData(deployResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param Error_details The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeError_details(writer: SerializationWriter, error_details: Partial<Error_details> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!error_details || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(error_details.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorEscaped The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorEscaped(writer: SerializationWriter, errorEscaped: Partial<ErrorEscaped> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorEscaped || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", errorEscaped.code);
    writer.writeObjectValue<Error_details>("details", errorEscaped.details, serializeError_details);
    writer.writeStringValue("error", errorEscaped.errorEscaped);
    writer.writeAdditionalData(errorEscaped.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProxyRoute The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProxyRoute(writer: SerializationWriter, proxyRoute: Partial<ProxyRoute> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!proxyRoute || isSerializingDerivedType) { return; }
    writer.writeStringValue("domain", proxyRoute.domain);
    writer.writeStringValue("upstream", proxyRoute.upstream);
    writer.writeAdditionalData(proxyRoute.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProxyStatus The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProxyStatus(writer: SerializationWriter, proxyStatus: Partial<ProxyStatus> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!proxyStatus || isSerializingDerivedType) { return; }
    writer.writeStringValue("status", proxyStatus.status);
    writer.writeAdditionalData(proxyStatus.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RegisterInstanceRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterInstanceRequest(writer: SerializationWriter, registerInstanceRequest: Partial<RegisterInstanceRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!registerInstanceRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("audience", registerInstanceRequest.audience);
    writer.writeStringValue("claim", registerInstanceRequest.claim);
    writer.writeStringValue("instance_id", registerInstanceRequest.instanceId);
    writer.writeStringValue("issuer", registerInstanceRequest.issuer);
    writer.writeAdditionalData(registerInstanceRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RemoteObj The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRemoteObj(writer: SerializationWriter, remoteObj: Partial<RemoteObj> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!remoteObj || isSerializingDerivedType) { return; }
    writer.writeStringValue("branch", remoteObj.branch);
    writer.writeStringValue("commit_hash", remoteObj.commitHash);
    writer.writeStringValue("url", remoteObj.url);
    writer.writeAdditionalData(remoteObj.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RuntimeObj The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRuntimeObj(writer: SerializationWriter, runtimeObj: Partial<RuntimeObj> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!runtimeObj || isSerializingDerivedType) { return; }
    writer.writeEnumValue<Runtime>("type", runtimeObj.type);
    writer.writeStringValue("version", runtimeObj.version);
    writer.writeAdditionalData(runtimeObj.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Service The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeService(writer: SerializationWriter, service: Partial<Service> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!service || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Blueprint>("blueprint", service.blueprint, serializeBlueprint);
    writer.writeStringValue("branch", service.branch);
    writer.writeStringValue("build_cmd", service.buildCmd);
    writer.writeStringValue("commit_hash", service.commitHash);
    writer.writeDateValue("created_at", service.createdAt);
    writer.writeStringValue("description", service.description);
    writer.writeObjectValue<Service_env_vars>("env_vars", service.envVars, serializeService_env_vars);
    writer.writeStringValue("id", service.id);
    writer.writeStringValue("image", service.image);
    writer.writeStringValue("name", service.name);
    writer.writeNumberValue("port", service.port);
    writer.writeStringValue("remote", service.remote);
    writer.writeStringValue("run_cmd", service.runCmd);
    writer.writeEnumValue<Runtime>("runtime", service.runtime);
    writer.writeStringValue("runtime_version", service.runtimeVersion);
    writer.writeStringValue("source", service.source);
    writer.writeStringValue("static_dir", service.staticDir);
    writer.writeStringValue("status", service.status);
    writer.writeDateValue("updated_at", service.updatedAt);
    writer.writeStringValue("working_dir", service.workingDir);
    writer.writeAdditionalData(service.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Service_env_vars The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeService_env_vars(writer: SerializationWriter, service_env_vars: Partial<Service_env_vars> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!service_env_vars || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(service_env_vars.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ServiceUpdate The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServiceUpdate(writer: SerializationWriter, serviceUpdate: Partial<ServiceUpdate> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!serviceUpdate || isSerializingDerivedType) { return; }
    writer.writeStringValue("branch", serviceUpdate.branch);
    writer.writeStringValue("build_cmd", serviceUpdate.buildCmd);
    writer.writeStringValue("description", serviceUpdate.description);
    writer.writeObjectValue<ServiceUpdate_env_vars>("env_vars", serviceUpdate.envVars, serializeServiceUpdate_env_vars);
    writer.writeStringValue("image", serviceUpdate.image);
    writer.writeStringValue("name", serviceUpdate.name);
    writer.writeNumberValue("port", serviceUpdate.port);
    writer.writeStringValue("run_cmd", serviceUpdate.runCmd);
    writer.writeStringValue("runtime_version", serviceUpdate.runtimeVersion);
    writer.writeStringValue("static_dir", serviceUpdate.staticDir);
    writer.writeStringValue("working_dir", serviceUpdate.workingDir);
    writer.writeAdditionalData(serviceUpdate.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ServiceUpdate_env_vars The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServiceUpdate_env_vars(writer: SerializationWriter, serviceUpdate_env_vars: Partial<ServiceUpdate_env_vars> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!serviceUpdate_env_vars || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(serviceUpdate_env_vars.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemDoctorResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemDoctorResult(writer: SerializationWriter, systemDoctorResult: Partial<SystemDoctorResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemDoctorResult || isSerializingDerivedType) { return; }
    writer.writeStringValue("error", systemDoctorResult.errorEscaped);
    writer.writeStringValue("output", systemDoctorResult.output);
    writer.writeStringValue("status", systemDoctorResult.status);
    writer.writeAdditionalData(systemDoctorResult.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemInfo The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemInfo(writer: SerializationWriter, systemInfo: Partial<SystemInfo> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemInfo || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SystemInfo_build>("build", systemInfo.build, serializeSystemInfo_build);
    writer.writeObjectValue<SystemInfo_hardware>("hardware", systemInfo.hardware, serializeSystemInfo_hardware);
    writer.writeObjectValue<SystemInfo_storage>("storage", systemInfo.storage, serializeSystemInfo_storage);
    writer.writeAdditionalData(systemInfo.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemInfo_build The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemInfo_build(writer: SerializationWriter, systemInfo_build: Partial<SystemInfo_build> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemInfo_build || isSerializingDerivedType) { return; }
    writer.writeStringValue("build_date", systemInfo_build.buildDate);
    writer.writeStringValue("commit", systemInfo_build.commit);
    writer.writeStringValue("go_version", systemInfo_build.goVersion);
    writer.writeStringValue("version", systemInfo_build.version);
    writer.writeAdditionalData(systemInfo_build.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemInfo_hardware The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemInfo_hardware(writer: SerializationWriter, systemInfo_hardware: Partial<SystemInfo_hardware> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemInfo_hardware || isSerializingDerivedType) { return; }
    writer.writeStringValue("arch", systemInfo_hardware.arch);
    writer.writeNumberValue("cpu_count", systemInfo_hardware.cpuCount);
    writer.writeStringValue("hostname", systemInfo_hardware.hostname);
    writer.writeStringValue("kernel", systemInfo_hardware.kernel);
    writer.writeStringValue("mem_free", systemInfo_hardware.memFree);
    writer.writeStringValue("mem_total", systemInfo_hardware.memTotal);
    writer.writeStringValue("mem_used", systemInfo_hardware.memUsed);
    writer.writeStringValue("os", systemInfo_hardware.os);
    writer.writeStringValue("swap_total", systemInfo_hardware.swapTotal);
    writer.writeStringValue("swap_used", systemInfo_hardware.swapUsed);
    writer.writeAdditionalData(systemInfo_hardware.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemInfo_storage The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemInfo_storage(writer: SerializationWriter, systemInfo_storage: Partial<SystemInfo_storage> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemInfo_storage || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<SystemInfo_storage_devices>("devices", systemInfo_storage.devices, serializeSystemInfo_storage_devices);
    writer.writeCollectionOfObjectValues<SystemInfo_storage_partitions>("partitions", systemInfo_storage.partitions, serializeSystemInfo_storage_partitions);
    writer.writeAdditionalData(systemInfo_storage.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemInfo_storage_devices The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemInfo_storage_devices(writer: SerializationWriter, systemInfo_storage_devices: Partial<SystemInfo_storage_devices> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemInfo_storage_devices || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("mountpoints", systemInfo_storage_devices.mountpoints);
    writer.writeStringValue("name", systemInfo_storage_devices.name);
    writer.writeStringValue("size", systemInfo_storage_devices.size);
    writer.writeStringValue("type", systemInfo_storage_devices.type);
    writer.writeAdditionalData(systemInfo_storage_devices.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemInfo_storage_partitions The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemInfo_storage_partitions(writer: SerializationWriter, systemInfo_storage_partitions: Partial<SystemInfo_storage_partitions> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemInfo_storage_partitions || isSerializingDerivedType) { return; }
    writer.writeStringValue("available", systemInfo_storage_partitions.available);
    writer.writeStringValue("filesystem", systemInfo_storage_partitions.filesystem);
    writer.writeStringValue("mountpoint", systemInfo_storage_partitions.mountpoint);
    writer.writeStringValue("size", systemInfo_storage_partitions.size);
    writer.writeStringValue("used", systemInfo_storage_partitions.used);
    writer.writeStringValue("use_percent", systemInfo_storage_partitions.usePercent);
    writer.writeAdditionalData(systemInfo_storage_partitions.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemStatus The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemStatus(writer: SerializationWriter, systemStatus: Partial<SystemStatus> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemStatus || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SystemStatus_proxy>("proxy", systemStatus.proxy, serializeSystemStatus_proxy);
    writer.writeObjectValue<SystemStatus_services>("services", systemStatus.services, serializeSystemStatus_services);
    writer.writeEnumValue<SystemStatus_status>("status", systemStatus.status);
    writer.writeStringValue("uptime", systemStatus.uptime);
    writer.writeAdditionalData(systemStatus.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemStatus_proxy The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemStatus_proxy(writer: SerializationWriter, systemStatus_proxy: Partial<SystemStatus_proxy> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemStatus_proxy || isSerializingDerivedType) { return; }
    writer.writeNumberValue("routes", systemStatus_proxy.routes);
    writer.writeStringValue("status", systemStatus_proxy.status);
    writer.writeAdditionalData(systemStatus_proxy.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SystemStatus_services The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSystemStatus_services(writer: SerializationWriter, systemStatus_services: Partial<SystemStatus_services> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!systemStatus_services || isSerializingDerivedType) { return; }
    writer.writeNumberValue("running", systemStatus_services.running);
    writer.writeNumberValue("stopped", systemStatus_services.stopped);
    writer.writeNumberValue("total", systemStatus_services.total);
    writer.writeAdditionalData(systemStatus_services.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ValidationError The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeValidationError(writer: SerializationWriter, validationError: Partial<ValidationError> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!validationError || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ValidationError_details>("details", validationError.details, serializeValidationError_details);
    writer.writeStringValue("error", validationError.errorEscaped);
    writer.writeAdditionalData(validationError.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ValidationError_details The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeValidationError_details(writer: SerializationWriter, validationError_details: Partial<ValidationError_details> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!validationError_details || isSerializingDerivedType) { return; }
    writer.writeStringValue("field", validationError_details.field);
    writer.writeStringValue("message", validationError_details.message);
    writer.writeAdditionalData(validationError_details.additionalData);
}
export interface Service extends AdditionalDataHolder, Parsable {
    /**
     * The blueprint property
     */
    blueprint?: Blueprint | null;
    /**
     * The branch property
     */
    branch?: string | null;
    /**
     * The build_cmd property
     */
    buildCmd?: string | null;
    /**
     * The commit_hash property
     */
    commitHash?: string | null;
    /**
     * The created_at property
     */
    createdAt?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The env_vars property
     */
    envVars?: Service_env_vars | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The port property
     */
    port?: number | null;
    /**
     * The remote property
     */
    remote?: string | null;
    /**
     * The run_cmd property
     */
    runCmd?: string | null;
    /**
     * The runtime property
     */
    runtime?: Runtime | null;
    /**
     * The runtime_version property
     */
    runtimeVersion?: string | null;
    /**
     * The source property
     */
    source?: string | null;
    /**
     * The static_dir property
     */
    staticDir?: string | null;
    /**
     * The status property
     */
    status?: string | null;
    /**
     * The updated_at property
     */
    updatedAt?: Date | null;
    /**
     * The working_dir property
     */
    workingDir?: string | null;
}
export interface Service_env_vars extends AdditionalDataHolder, Parsable {
}
export interface ServiceUpdate extends AdditionalDataHolder, Parsable {
    /**
     * The branch property
     */
    branch?: string | null;
    /**
     * The build_cmd property
     */
    buildCmd?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The env_vars property
     */
    envVars?: ServiceUpdate_env_vars | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The port property
     */
    port?: number | null;
    /**
     * The run_cmd property
     */
    runCmd?: string | null;
    /**
     * The runtime_version property
     */
    runtimeVersion?: string | null;
    /**
     * The static_dir property
     */
    staticDir?: string | null;
    /**
     * The working_dir property
     */
    workingDir?: string | null;
}
export interface ServiceUpdate_env_vars extends AdditionalDataHolder, Parsable {
}
export interface SystemDoctorResult extends AdditionalDataHolder, Parsable {
    /**
     * Error message if status is "error"
     */
    errorEscaped?: string | null;
    /**
     * Combined textual output from the doctor/install scripts
     */
    output?: string | null;
    /**
     * The status property
     */
    status?: string | null;
}
export interface SystemInfo extends AdditionalDataHolder, Parsable {
    /**
     * The build property
     */
    build?: SystemInfo_build | null;
    /**
     * The hardware property
     */
    hardware?: SystemInfo_hardware | null;
    /**
     * The storage property
     */
    storage?: SystemInfo_storage | null;
}
export interface SystemInfo_build extends AdditionalDataHolder, Parsable {
    /**
     * Build date - bundled at build time
     */
    buildDate?: string | null;
    /**
     * The commit property
     */
    commit?: string | null;
    /**
     * The go_version property
     */
    goVersion?: string | null;
    /**
     * The version property
     */
    version?: string | null;
}
export interface SystemInfo_hardware extends AdditionalDataHolder, Parsable {
    /**
     * The arch property
     */
    arch?: string | null;
    /**
     * The cpu_count property
     */
    cpuCount?: number | null;
    /**
     * The hostname property
     */
    hostname?: string | null;
    /**
     * The kernel property
     */
    kernel?: string | null;
    /**
     * The mem_free property
     */
    memFree?: string | null;
    /**
     * The mem_total property
     */
    memTotal?: string | null;
    /**
     * The mem_used property
     */
    memUsed?: string | null;
    /**
     * The os property
     */
    os?: string | null;
    /**
     * The swap_total property
     */
    swapTotal?: string | null;
    /**
     * The swap_used property
     */
    swapUsed?: string | null;
}
export interface SystemInfo_storage extends AdditionalDataHolder, Parsable {
    /**
     * The devices property
     */
    devices?: SystemInfo_storage_devices[] | null;
    /**
     * The partitions property
     */
    partitions?: SystemInfo_storage_partitions[] | null;
}
export interface SystemInfo_storage_devices extends AdditionalDataHolder, Parsable {
    /**
     * The mountpoints property
     */
    mountpoints?: string[] | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The size property
     */
    size?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface SystemInfo_storage_partitions extends AdditionalDataHolder, Parsable {
    /**
     * The available property
     */
    available?: string | null;
    /**
     * The filesystem property
     */
    filesystem?: string | null;
    /**
     * The mountpoint property
     */
    mountpoint?: string | null;
    /**
     * The size property
     */
    size?: string | null;
    /**
     * The used property
     */
    used?: string | null;
    /**
     * The use_percent property
     */
    usePercent?: string | null;
}
export interface SystemStatus extends AdditionalDataHolder, Parsable {
    /**
     * The proxy property
     */
    proxy?: SystemStatus_proxy | null;
    /**
     * The services property
     */
    services?: SystemStatus_services | null;
    /**
     * The status property
     */
    status?: SystemStatus_status | null;
    /**
     * System uptime duration
     */
    uptime?: string | null;
}
export interface SystemStatus_proxy extends AdditionalDataHolder, Parsable {
    /**
     * The routes property
     */
    routes?: number | null;
    /**
     * The status property
     */
    status?: string | null;
}
export interface SystemStatus_services extends AdditionalDataHolder, Parsable {
    /**
     * The running property
     */
    running?: number | null;
    /**
     * The stopped property
     */
    stopped?: number | null;
    /**
     * The total property
     */
    total?: number | null;
}
export type SystemStatus_status = (typeof SystemStatus_statusObject)[keyof typeof SystemStatus_statusObject];
export interface ValidationError extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The details property
     */
    details?: ValidationError_details[] | null;
    /**
     * The error property
     */
    errorEscaped?: string | null;
}
export interface ValidationError_details extends AdditionalDataHolder, Parsable {
    /**
     * The field property
     */
    field?: string | null;
    /**
     * The message property
     */
    message?: string | null;
}
export const Blueprint_sourceObject = {
    Remote: "remote",
    Image: "image",
} as const;
export const DeploymentStatusObject = {
    Pending: "pending",
    In_progress: "in_progress",
    Failed: "failed",
    Completed: "completed",
} as const;
export const DeployRequest_sourceObject = {
    Remote: "remote",
    Image: "image",
} as const;
export const RuntimeObject = {
    Static: "static",
    Golang: "golang",
    Php: "php",
    Python: "python",
    Nodejs: "nodejs",
    Ruby: "ruby",
    Dotnet: "dotnet",
    Java: "java",
    Docker: "docker",
    K3s: "k3s",
    Custom: "custom",
} as const;
export const SystemStatus_statusObject = {
    Healthy: "healthy",
    Degraded: "degraded",
    Unhealthy: "unhealthy",
} as const;
/* tslint:enable */
/* eslint-enable */
