/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RoleRequestBuilderRequestsMetadata, type RoleRequestBuilder } from './role/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /users/{email}
 */
export interface WithEmailItemRequestBuilder extends BaseRequestBuilder<WithEmailItemRequestBuilder> {
    /**
     * The role property
     */
    get role(): RoleRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithEmailItemRequestBuilderUriTemplate = "{+baseurl}/users/{email}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithEmailItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithEmailItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    role: {
        requestsMetadata: RoleRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
