/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, type ErrorEscaped } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RestartPostResponse}
 */
// @ts-ignore
export function createRestartPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRestartPostResponse;
}
/**
 * The deserialization information for the current model
 * @param RestartPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRestartPostResponse(restartPostResponse: Partial<RestartPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { restartPostResponse.message = n.getStringValue(); },
    }
}
export interface RestartPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
}
/**
 * Builds and executes requests for operations under /proxy/restart
 */
export interface RestartRequestBuilder extends BaseRequestBuilder<RestartRequestBuilder> {
    /**
     * Restart the proxy service (Admin+ required)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RestartPostResponse>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 403 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RestartPostResponse | undefined>;
    /**
     * Restart the proxy service (Admin+ required)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RestartPostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRestartPostResponse(writer: SerializationWriter, restartPostResponse: Partial<RestartPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!restartPostResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", restartPostResponse.message);
    writer.writeAdditionalData(restartPostResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const RestartRequestBuilderUriTemplate = "{+baseurl}/proxy/restart";
/**
 * Metadata for all the requests in the request builder.
 */
export const RestartRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RestartRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRestartPostResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
