/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, type ErrorEscaped } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RemoveDeleteResponse}
 */
// @ts-ignore
export function createRemoveDeleteResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRemoveDeleteResponse;
}
/**
 * The deserialization information for the current model
 * @param RemoveDeleteResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRemoveDeleteResponse(removeDeleteResponse: Partial<RemoveDeleteResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { removeDeleteResponse.message = n.getStringValue(); },
    }
}
export interface RemoveDeleteResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
}
/**
 * Builds and executes requests for operations under /proxy/remove
 */
export interface RemoveRequestBuilder extends BaseRequestBuilder<RemoveRequestBuilder> {
    /**
     * Remove a route from the proxy configuration (Admin+ required)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RemoveDeleteResponse>}
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 403 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RemoveDeleteResponse | undefined>;
    /**
     * Remove a route from the proxy configuration (Admin+ required)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RemoveDeleteResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRemoveDeleteResponse(writer: SerializationWriter, removeDeleteResponse: Partial<RemoveDeleteResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!removeDeleteResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", removeDeleteResponse.message);
    writer.writeAdditionalData(removeDeleteResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const RemoveRequestBuilderUriTemplate = "{+baseurl}/proxy/remove";
/**
 * Metadata for all the requests in the request builder.
 */
export const RemoveRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: RemoveRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRemoveDeleteResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
