/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, type ErrorEscaped } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RefreshPostRequestBody}
 */
// @ts-ignore
export function createRefreshPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRefreshPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RefreshPostResponse}
 */
// @ts-ignore
export function createRefreshPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRefreshPostResponse;
}
/**
 * The deserialization information for the current model
 * @param RefreshPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRefreshPostRequestBody(refreshPostRequestBody: Partial<RefreshPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "refresh_token": n => { refreshPostRequestBody.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RefreshPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRefreshPostResponse(refreshPostResponse: Partial<RefreshPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access_token": n => { refreshPostResponse.accessToken = n.getStringValue(); },
        "token_type": n => { refreshPostResponse.tokenType = n.getStringValue(); },
    }
}
export interface RefreshPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Valid refresh token
     */
    refreshToken?: string | null;
}
export interface RefreshPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * New JWT access token (10 minute lifespan)
     */
    accessToken?: string | null;
    /**
     * The token_type property
     */
    tokenType?: string | null;
}
/**
 * Builds and executes requests for operations under /auth/refresh
 */
export interface RefreshRequestBuilder extends BaseRequestBuilder<RefreshRequestBuilder> {
    /**
     * Generate a new access token using a valid refresh token.The refresh token must be of type "refresh" and not expired.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RefreshPostResponse>}
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     post(body: RefreshPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RefreshPostResponse | undefined>;
    /**
     * Generate a new access token using a valid refresh token.The refresh token must be of type "refresh" and not expired.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RefreshPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RefreshPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRefreshPostRequestBody(writer: SerializationWriter, refreshPostRequestBody: Partial<RefreshPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!refreshPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("refresh_token", refreshPostRequestBody.refreshToken);
    writer.writeAdditionalData(refreshPostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RefreshPostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRefreshPostResponse(writer: SerializationWriter, refreshPostResponse: Partial<RefreshPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!refreshPostResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("access_token", refreshPostResponse.accessToken);
    writer.writeStringValue("token_type", refreshPostResponse.tokenType);
    writer.writeAdditionalData(refreshPostResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const RefreshRequestBuilderUriTemplate = "{+baseurl}/auth/refresh";
/**
 * Metadata for all the requests in the request builder.
 */
export const RefreshRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RefreshRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRefreshPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRefreshPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
