/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RefreshRequestBuilderRequestsMetadata, type RefreshRequestBuilder } from './refresh/index.js';
// @ts-ignore
import { RequestRequestBuilderRequestsMetadata, type RequestRequestBuilder } from './request/index.js';
// @ts-ignore
import { type VerifyRequestBuilder, VerifyRequestBuilderRequestsMetadata } from './verify/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The refresh property
     */
    get refresh(): RefreshRequestBuilder;
    /**
     * The request property
     */
    get request(): RequestRequestBuilder;
    /**
     * The verify property
     */
    get verify(): VerifyRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    refresh: {
        requestsMetadata: RefreshRequestBuilderRequestsMetadata,
    },
    request: {
        requestsMetadata: RequestRequestBuilderRequestsMetadata,
    },
    verify: {
        requestsMetadata: VerifyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
