/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createSystemDoctorResultFromDiscriminatorValue, type ErrorEscaped, type SystemDoctorResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /system/doctor
 */
export interface DoctorRequestBuilder extends BaseRequestBuilder<DoctorRequestBuilder> {
    /**
     * Run system diagnostics and attempt auto-fixes for core dependencies.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SystemDoctorResult>}
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SystemDoctorResult | undefined>;
    /**
     * Run system diagnostics and attempt auto-fixes for core dependencies.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DoctorRequestBuilderUriTemplate = "{+baseurl}/system/doctor";
/**
 * Metadata for all the requests in the request builder.
 */
export const DoctorRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DoctorRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSystemDoctorResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
