from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ...models.error import Error

class StreamRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /logs/stream
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new StreamRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/logs/stream?id={id}&token={token}", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[StreamRequestBuilderGetQueryParameters]] = None) -> Optional[bytes]:
        """
        Open a keep alive connection to stream logs via server sent events (SSE) (Developer+ required).- `data:` events contain log lines- `event: error` indicates streaming errors- `event: done` indicates stream completion- `: heartbeat` every 15 seconds to keep the connection alive
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: bytes
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from ...models.error import Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "400": Error,
            "401": Error,
            "403": Error,
            "405": Error,
            "500": Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        return await self.request_adapter.send_primitive_async(request_info, "bytes", error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[StreamRequestBuilderGetQueryParameters]] = None) -> RequestInformation:
        """
        Open a keep alive connection to stream logs via server sent events (SSE) (Developer+ required).- `data:` events contain log lines- `event: error` indicates streaming errors- `event: done` indicates stream completion- `: heartbeat` every 15 seconds to keep the connection alive
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "text/event-stream, application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> StreamRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: StreamRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return StreamRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class StreamRequestBuilderGetQueryParameters():
        """
        Open a keep alive connection to stream logs via server sent events (SSE) (Developer+ required).- `data:` events contain log lines- `event: error` indicates streaming errors- `event: done` indicates stream completion- `: heartbeat` every 15 seconds to keep the connection alive
        """
        # Service or deployment ID to stream logs for
        id: Optional[str] = None

        # Bearer token for authentication
        token: Optional[str] = None

    
    @dataclass
    class StreamRequestBuilderGetRequestConfiguration(RequestConfiguration[StreamRequestBuilderGetQueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

