/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AddRequestBuilderRequestsMetadata, type AddRequestBuilder } from './add/index.js';
// @ts-ignore
import { RemoveRequestBuilderRequestsMetadata, type RemoveRequestBuilder } from './remove/index.js';
// @ts-ignore
import { RestartRequestBuilderRequestsMetadata, type RestartRequestBuilder } from './restart/index.js';
// @ts-ignore
import { StatusRequestBuilderRequestsMetadata, type StatusRequestBuilder } from './status/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /proxy
 */
export interface ProxyRequestBuilder extends BaseRequestBuilder<ProxyRequestBuilder> {
    /**
     * The add property
     */
    get add(): AddRequestBuilder;
    /**
     * The remove property
     */
    get remove(): RemoveRequestBuilder;
    /**
     * The restart property
     */
    get restart(): RestartRequestBuilder;
    /**
     * The status property
     */
    get status(): StatusRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProxyRequestBuilderUriTemplate = "{+baseurl}/proxy";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProxyRequestBuilderNavigationMetadata: Record<Exclude<keyof ProxyRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    add: {
        requestsMetadata: AddRequestBuilderRequestsMetadata,
    },
    remove: {
        requestsMetadata: RemoveRequestBuilderRequestsMetadata,
    },
    restart: {
        requestsMetadata: RestartRequestBuilderRequestsMetadata,
    },
    status: {
        requestsMetadata: StatusRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
