/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDeploymentFromDiscriminatorValue, createDeployResponseFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, createValidationErrorFromDiscriminatorValue, serializeDeployment, serializeDeployRequest, serializeDeployResponse, type Deployment, type DeployRequest, type DeployResponse, type ErrorEscaped, type ValidationError } from '../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeploymentsGetResponse}
 */
// @ts-ignore
export function createDeploymentsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeploymentsGetResponse;
}
export interface DeploymentsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The deployments property
     */
    deployments?: Deployment[] | null;
    /**
     * Total number of deployments
     */
    total?: number | null;
}
/**
 * Builds and executes requests for operations under /deployments
 */
export interface DeploymentsRequestBuilder extends BaseRequestBuilder<DeploymentsRequestBuilder> {
    /**
     * Retrieve a list of deployments (Developer+ required)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DeploymentsGetResponse>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 403 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<DeploymentsRequestBuilderGetQueryParameters> | undefined) : Promise<DeploymentsGetResponse | undefined>;
    /**
     * Create a new deployment (Developer+ required)
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DeployResponse>}
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 403 status code
     * @throws {ValidationError} error when the service returns a 422 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     post(body: DeployRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DeployResponse | undefined>;
    /**
     * Retrieve a list of deployments (Developer+ required)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DeploymentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a new deployment (Developer+ required)
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: DeployRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Retrieve a list of deployments (Developer+ required)
 */
export interface DeploymentsRequestBuilderGetQueryParameters {
    /**
     * Maximum number of deployments to return
     */
    limit?: number;
    /**
     * Number of deployments to skip
     */
    offset?: number;
}
/**
 * The deserialization information for the current model
 * @param DeploymentsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeploymentsGetResponse(deploymentsGetResponse: Partial<DeploymentsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "deployments": n => { deploymentsGetResponse.deployments = n.getCollectionOfObjectValues<Deployment>(createDeploymentFromDiscriminatorValue); },
        "total": n => { deploymentsGetResponse.total = n.getNumberValue(); },
    }
}
/**
 * Serializes information the current object
 * @param DeploymentsGetResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeploymentsGetResponse(writer: SerializationWriter, deploymentsGetResponse: Partial<DeploymentsGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deploymentsGetResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Deployment>("deployments", deploymentsGetResponse.deployments, serializeDeployment);
    writer.writeNumberValue("total", deploymentsGetResponse.total);
    writer.writeAdditionalData(deploymentsGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const DeploymentsRequestBuilderUriTemplate = "{+baseurl}/deployments{?limit*,offset*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const DeploymentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DeploymentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDeploymentsGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: DeploymentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDeployResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDeployRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
