/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DoctorRequestBuilderRequestsMetadata, type DoctorRequestBuilder } from './doctor/index.js';
// @ts-ignore
import { DomainRequestBuilderRequestsMetadata, type DomainRequestBuilder } from './domain/index.js';
// @ts-ignore
import { InfoRequestBuilderRequestsMetadata, type InfoRequestBuilder } from './info/index.js';
// @ts-ignore
import { InstallRequestBuilderRequestsMetadata, type InstallRequestBuilder } from './install/index.js';
// @ts-ignore
import { RegisterRequestBuilderRequestsMetadata, type RegisterRequestBuilder } from './register/index.js';
// @ts-ignore
import { StatusRequestBuilderRequestsMetadata, type StatusRequestBuilder } from './status/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /system
 */
export interface SystemRequestBuilder extends BaseRequestBuilder<SystemRequestBuilder> {
    /**
     * The doctor property
     */
    get doctor(): DoctorRequestBuilder;
    /**
     * The domain property
     */
    get domain(): DomainRequestBuilder;
    /**
     * The info property
     */
    get info(): InfoRequestBuilder;
    /**
     * The install property
     */
    get install(): InstallRequestBuilder;
    /**
     * The register property
     */
    get register(): RegisterRequestBuilder;
    /**
     * The status property
     */
    get status(): StatusRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SystemRequestBuilderUriTemplate = "{+baseurl}/system";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SystemRequestBuilderNavigationMetadata: Record<Exclude<keyof SystemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    doctor: {
        requestsMetadata: DoctorRequestBuilderRequestsMetadata,
    },
    domain: {
        requestsMetadata: DomainRequestBuilderRequestsMetadata,
    },
    info: {
        requestsMetadata: InfoRequestBuilderRequestsMetadata,
    },
    install: {
        requestsMetadata: InstallRequestBuilderRequestsMetadata,
    },
    register: {
        requestsMetadata: RegisterRequestBuilderRequestsMetadata,
    },
    status: {
        requestsMetadata: StatusRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
