/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { InfoRequestBuilderRequestsMetadata, type InfoRequestBuilder } from './info/index.js';
// @ts-ignore
import { StatusRequestBuilderRequestsMetadata, type StatusRequestBuilder } from './status/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /system
 */
export interface SystemRequestBuilder extends BaseRequestBuilder<SystemRequestBuilder> {
    /**
     * The info property
     */
    get info(): InfoRequestBuilder;
    /**
     * The status property
     */
    get status(): StatusRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SystemRequestBuilderUriTemplate = "{+baseurl}/system";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SystemRequestBuilderNavigationMetadata: Record<Exclude<keyof SystemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    info: {
        requestsMetadata: InfoRequestBuilderRequestsMetadata,
    },
    status: {
        requestsMetadata: StatusRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
