/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { StreamRequestBuilderRequestsMetadata, type StreamRequestBuilder } from './stream/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /logs
 */
export interface LogsRequestBuilder extends BaseRequestBuilder<LogsRequestBuilder> {
    /**
     * The stream property
     */
    get stream(): StreamRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const LogsRequestBuilderUriTemplate = "{+baseurl}/logs";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LogsRequestBuilderNavigationMetadata: Record<Exclude<keyof LogsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    stream: {
        requestsMetadata: StreamRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
