/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createLoginResponseFromDiscriminatorValue, serializeLoginResponse, type ErrorEscaped, type LoginResponse } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RequestPostRequestBody}
 */
// @ts-ignore
export function createRequestPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRequestPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param RequestPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRequestPostRequestBody(requestPostRequestBody: Partial<RequestPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { requestPostRequestBody.email = n.getStringValue(); },
        "lifespan": n => { requestPostRequestBody.lifespan = n.getStringValue(); },
        "secret": n => { requestPostRequestBody.secret = n.getStringValue(); },
        "username": n => { requestPostRequestBody.username = n.getStringValue(); },
    }
}
export interface RequestPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * User email address
     */
    email?: string | null;
    /**
     * Refresh token lifespan (e.g., "24h", "7d", "never")
     */
    lifespan?: string | null;
    /**
     * Owner secret key (required only for first owner creation)
     */
    secret?: string | null;
    /**
     * System username for role determination via groups
     */
    username?: string | null;
}
/**
 * Builds and executes requests for operations under /auth/request
 */
export interface RequestRequestBuilder extends BaseRequestBuilder<RequestRequestBuilder> {
    /**
     * Generate JWT access and refresh tokens for authentication.**Owner Bootstrap**: First-time setup requires a secret key to create the owner user.**Role Assignment**: Users are assigned roles based on system groups or explicit owner creation.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LoginResponse>}
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     post(body: RequestPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LoginResponse | undefined>;
    /**
     * Generate JWT access and refresh tokens for authentication.**Owner Bootstrap**: First-time setup requires a secret key to create the owner user.**Role Assignment**: Users are assigned roles based on system groups or explicit owner creation.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RequestPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRequestPostRequestBody(writer: SerializationWriter, requestPostRequestBody: Partial<RequestPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!requestPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", requestPostRequestBody.email);
    writer.writeStringValue("lifespan", requestPostRequestBody.lifespan);
    writer.writeStringValue("secret", requestPostRequestBody.secret);
    writer.writeStringValue("username", requestPostRequestBody.username);
    writer.writeAdditionalData(requestPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const RequestRequestBuilderUriTemplate = "{+baseurl}/auth/request";
/**
 * Metadata for all the requests in the request builder.
 */
export const RequestRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RequestRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLoginResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
