/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createUserFromDiscriminatorValue, Role, RoleObject, serializeUser, type ErrorEscaped, type User } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RolePutRequestBody}
 */
// @ts-ignore
export function createRolePutRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRolePutRequestBody;
}
/**
 * The deserialization information for the current model
 * @param RolePutRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRolePutRequestBody(rolePutRequestBody: Partial<RolePutRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "role": n => { rolePutRequestBody.role = n.getEnumValue<Role>(RoleObject); },
    }
}
export interface RolePutRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * User role hierarchy (owner > admin > developer > viewer):- **owner**: Full system control, manage admins, uninstall dployr- **admin**: Infrastructure management, secrets, users, proxies, shell access- **developer**: Deploy apps, view logs, events, resource graph- **viewer**: Read-only access to services
     */
    role?: Role | null;
}
/**
 * Builds and executes requests for operations under /users/{email}/role
 */
export interface RoleRequestBuilder extends BaseRequestBuilder<RoleRequestBuilder> {
    /**
     * Update a user's role (Admin+ required, Owner required to create/modify admins)
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<User>}
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 403 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     put(body: RolePutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<User | undefined>;
    /**
     * Update a user's role (Admin+ required, Owner required to create/modify admins)
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: RolePutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RolePutRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRolePutRequestBody(writer: SerializationWriter, rolePutRequestBody: Partial<RolePutRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!rolePutRequestBody || isSerializingDerivedType) { return; }
    writer.writeEnumValue<Role>("role", rolePutRequestBody.role);
    writer.writeAdditionalData(rolePutRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const RoleRequestBuilderUriTemplate = "{+baseurl}/users/{email}/role";
/**
 * Metadata for all the requests in the request builder.
 */
export const RoleRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: RoleRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRolePutRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
