/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, type ErrorEscaped } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /logs/stream
 */
export interface StreamRequestBuilder extends BaseRequestBuilder<StreamRequestBuilder> {
    /**
     * Open a keep alive connection to stream logs via server sent events (SSE) (Developer+ required).- `data:` events contain log lines- `event: error` indicates streaming errors- `event: done` indicates stream completion- `: heartbeat` every 15 seconds to keep the connection alive
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 403 status code
     * @throws {ErrorEscaped} error when the service returns a 405 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<StreamRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Open a keep alive connection to stream logs via server sent events (SSE) (Developer+ required).- `data:` events contain log lines- `event: error` indicates streaming errors- `event: done` indicates stream completion- `: heartbeat` every 15 seconds to keep the connection alive
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StreamRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Open a keep alive connection to stream logs via server sent events (SSE) (Developer+ required).- `data:` events contain log lines- `event: error` indicates streaming errors- `event: done` indicates stream completion- `: heartbeat` every 15 seconds to keep the connection alive
 */
export interface StreamRequestBuilderGetQueryParameters {
    /**
     * Service or deployment ID to stream logs for
     */
    id?: string;
    /**
     * Bearer token for authentication
     */
    token?: string;
}
/**
 * Uri template for the request builder.
 */
export const StreamRequestBuilderUriTemplate = "{+baseurl}/logs/stream?id={id}&token={token}";
/**
 * Metadata for all the requests in the request builder.
 */
export const StreamRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StreamRequestBuilderUriTemplate,
        responseBodyContentType: "text/event-stream, application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            405: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
