/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, type ErrorEscaped } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /logs/stream
 */
export interface StreamRequestBuilder extends BaseRequestBuilder<StreamRequestBuilder> {
    /**
     * Open a WebSocket connection to stream logs in real-time (Developer+ required).This endpoint upgrades the HTTP connection to WebSocket.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 403 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<StreamRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Open a WebSocket connection to stream logs in real-time (Developer+ required).This endpoint upgrades the HTTP connection to WebSocket.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StreamRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Open a WebSocket connection to stream logs in real-time (Developer+ required).This endpoint upgrades the HTTP connection to WebSocket.
 */
export interface StreamRequestBuilderGetQueryParameters {
    /**
     * Deployment ID to stream logs for
     */
    deploymentId?: string;
    /**
     * Service ID to stream logs for
     */
    serviceId?: string;
}
/**
 * Uri template for the request builder.
 */
export const StreamRequestBuilderUriTemplate = "{+baseurl}/logs/stream{?deployment_id*,service_id*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const StreamRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "deploymentId": "deployment_id",
    "serviceId": "service_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const StreamRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StreamRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        queryParametersMapper: StreamRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
