/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createServiceFromDiscriminatorValue, serializeService, type ErrorEscaped, type Service } from '../models/index.js';
// @ts-ignore
import { type WithServiceItemRequestBuilder, WithServiceItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServicesGetResponse}
 */
// @ts-ignore
export function createServicesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServicesGetResponse;
}
/**
 * The deserialization information for the current model
 * @param ServicesGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServicesGetResponse(servicesGetResponse: Partial<ServicesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "services": n => { servicesGetResponse.services = n.getCollectionOfObjectValues<Service>(createServiceFromDiscriminatorValue); },
        "total": n => { servicesGetResponse.total = n.getNumberValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ServicesGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServicesGetResponse(writer: SerializationWriter, servicesGetResponse: Partial<ServicesGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!servicesGetResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Service>("services", servicesGetResponse.services, serializeService);
    writer.writeNumberValue("total", servicesGetResponse.total);
    writer.writeAdditionalData(servicesGetResponse.additionalData);
}
export interface ServicesGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The services property
     */
    services?: Service[] | null;
    /**
     * The total property
     */
    total?: number | null;
}
/**
 * Builds and executes requests for operations under /services
 */
export interface ServicesRequestBuilder extends BaseRequestBuilder<ServicesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.services.item collection
     * @param serviceId Service ID
     * @returns {WithServiceItemRequestBuilder}
     */
     byServiceId(serviceId: string) : WithServiceItemRequestBuilder;
    /**
     * Retrieve a list of services (Viewer+ required)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServicesGetResponse>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 403 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<ServicesRequestBuilderGetQueryParameters> | undefined) : Promise<ServicesGetResponse | undefined>;
    /**
     * Retrieve a list of services (Viewer+ required)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ServicesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a list of services (Viewer+ required)
 */
export interface ServicesRequestBuilderGetQueryParameters {
    /**
     * Maximum number of services to return
     */
    limit?: number;
    /**
     * Number of services to skip
     */
    offset?: number;
}
/**
 * Uri template for the request builder.
 */
export const ServicesRequestBuilderUriTemplate = "{+baseurl}/services{?limit*,offset*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ServicesRequestBuilderNavigationMetadata: Record<Exclude<keyof ServicesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byServiceId: {
        requestsMetadata: WithServiceItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["serviceId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ServicesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ServicesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createServicesGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
