/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createSystemDoctorResultFromDiscriminatorValue, serializeInstallRequest, serializeSystemDoctorResult, type ErrorEscaped, type InstallRequest, type SystemDoctorResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /system/install
 */
export interface InstallRequestBuilder extends BaseRequestBuilder<InstallRequestBuilder> {
    /**
     * Install a specific version of dployr or the latest version, then run the system doctor.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SystemDoctorResult>}
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     post(body: InstallRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SystemDoctorResult | undefined>;
    /**
     * Install a specific version of dployr or the latest version, then run the system doctor.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: InstallRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InstallRequestBuilderUriTemplate = "{+baseurl}/system/install";
/**
 * Metadata for all the requests in the request builder.
 */
export const InstallRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: InstallRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSystemDoctorResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeInstallRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
