/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createSystemDoctorResultFromDiscriminatorValue, serializeSystemDoctorResult, type ErrorEscaped, type SystemDoctorResult } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InstallPostRequestBody}
 */
// @ts-ignore
export function createInstallPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInstallPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param InstallPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInstallPostRequestBody(installPostRequestBody: Partial<InstallPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "version": n => { installPostRequestBody.version = n.getStringValue(); },
    }
}
export interface InstallPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * dployr version tag to install (e.g. v0.1.1-beta.17). If omitted, installs latest.
     */
    version?: string | null;
}
/**
 * Builds and executes requests for operations under /system/install
 */
export interface InstallRequestBuilder extends BaseRequestBuilder<InstallRequestBuilder> {
    /**
     * Install a specific version of dployr or the latest version, then run the system doctor.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SystemDoctorResult>}
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     */
     post(body: InstallPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SystemDoctorResult | undefined>;
    /**
     * Install a specific version of dployr or the latest version, then run the system doctor.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: InstallPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param InstallPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInstallPostRequestBody(writer: SerializationWriter, installPostRequestBody: Partial<InstallPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!installPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("version", installPostRequestBody.version);
    writer.writeAdditionalData(installPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const InstallRequestBuilderUriTemplate = "{+baseurl}/system/install";
/**
 * Metadata for all the requests in the request builder.
 */
export const InstallRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: InstallRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSystemDoctorResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeInstallPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
